### ISSUE TITLE
Things I want to see wrapped up and merged soon

### ISSUE THREAD

**Issue by reaperrr** [reaperrr/OpenRA#10]
Most important to me personally:
- [ ] #8717 (so I can ditch my hacky BallisticMissile from TDX)
- [ ] #9174
- [ ] #9309

Must be finished for next release to be playable in MP:
- [ ] original D2k balancing

Would be better if finished soon:
- [ ] TraitInfo refactorings (just so we can get used to the full set of changes as quickly as possible)
- [ ] #9262 (performance improvement is quite noticable with many frozen actors)

**Comment by phrohdoh** [comment]
Hey, just so you're aware; all referenced PRs have been merged.

**Comment by reaperrr** [comment]
You're right, thanks.
